name: Test Build

on:
  workflow_dispatch:
    inputs:
      tags:
        description: 'Enter the version number, without the "v"'
        required: true
        type: string
  # push:
  #   tags: [ v\d+\.\d+\.\d+ ]

jobs:
  log-the-inputs:
    runs-on: ubuntu-latest
    steps:
      - name: Echo Inputs
        run: |
          echo "Tags: $TAGS"
        env:
          TAGS: ${{ inputs.tags }}

  get-inputs:
    runs-on: ubuntu-22.04
    steps:
      - name: Show Inputs
        env:
          VERSION: "${{ inputs.tags }}"
        run: |
          echo "Inputs Tags: ${{ inputs.tags }}"
